import { defineConfig } from 'vite'
import tailwindcss from '@tailwindcss/vite'
import { resolve } from 'node:path'
const root = import.meta.dirname
export default defineConfig({
  base: '/bancrofts-wireframes/',
  plugins: [tailwindcss()],
  build: {
    rollupOptions: {
      input: {
        index: resolve(root, 'index.html'),
        admissions: resolve(root, 'admissions.html'),
        admissions_7plus_journey: resolve(root, 'admissions-7plus-journey.html'),
        admissions_11plus_journey: resolve(root, 'admissions-11plus-journey.html'),
        admissions_16plus_journey: resolve(root, 'admissions-16plus-journey.html'),
        book_a_visit: resolve(root, 'book-a-visit.html'),
        register: resolve(root, 'register.html'),
        fees: resolve(root, 'fees.html'),
        scholarships_bursaries: resolve(root, 'scholarships-bursaries.html'),
        admissions_faqs: resolve(root, 'admissions-faqs.html'),
        prep: resolve(root, 'prep.html'),
        prep_why: resolve(root, 'prep-why.html'),
        prep_curriculum: resolve(root, 'prep-curriculum.html'),
        prep_clubs: resolve(root, 'prep-clubs.html'),
        prep_pastoral_care: resolve(root, 'prep-pastoral-care.html'),
        prep_staff: resolve(root, 'prep-staff.html'),
        senior: resolve(root, 'senior.html'),
        senior_why: resolve(root, 'senior-why.html'),
        senior_academic_results: resolve(root, 'senior-academic-results.html'),
        senior_curriculum: resolve(root, 'senior-curriculum.html'),
        senior_sport_arts: resolve(root, 'senior-sport-arts.html'),
        senior_clubs: resolve(root, 'senior-clubs.html'),
        senior_pastoral_care: resolve(root, 'senior-pastoral-care.html'),
        senior_sport: resolve(root, 'senior-sport.html'),
        senior_sport_football: resolve(root, 'senior-sport-football.html'),
        senior_sport_rugby: resolve(root, 'senior-sport-rugby.html'),
        senior_sport_hockey: resolve(root, 'senior-sport-hockey.html'),
        senior_sport_netball: resolve(root, 'senior-sport-netball.html'),
        senior_sport_cricket: resolve(root, 'senior-sport-cricket.html'),
        senior_sport_athletics: resolve(root, 'senior-sport-athletics.html'),
        senior_sport_swimming: resolve(root, 'senior-sport-swimming.html'),
        senior_sport_tennis: resolve(root, 'senior-sport-tennis.html'),
        senior_sport_badminton: resolve(root, 'senior-sport-badminton.html'),
        sixth_form: resolve(root, 'sixth-form.html'),
        sixth_form_life: resolve(root, 'sixth-form-life.html'),
        sixth_form_clubs: resolve(root, 'sixth-form-clubs.html'),
        sixth_form_curriculum_subjects: resolve(root, 'sixth-form-curriculum-subjects.html'),
        sixth_form_leavers_destinations: resolve(root, 'sixth-form-leavers-destinations.html'),
        sixth_form_staying_on: resolve(root, 'sixth-form-staying-on.html'),
        sixth_form_examination_results: resolve(root, 'sixth-form-examination-results.html'),
        school_life: resolve(root, 'school-life.html'),
        school_life_community: resolve(root, 'school-life-community.html'),
        calendar: resolve(root, 'calendar.html'),
        weekly_menu: resolve(root, 'weekly-menu.html'),
        school_bus_service: resolve(root, 'school-bus-service.html'),
        news: resolve(root, 'news.html'),
        news_article_a: resolve(root, 'news-article-a.html'),
        news_article_b: resolve(root, 'news-article-b.html'),
        news_article_c: resolve(root, 'news-article-c.html'),
        about: resolve(root, 'about.html'),
        about_welcome: resolve(root, 'about-welcome.html'),
        about_what_we_stand_for: resolve(root, 'about-what-we-stand-for.html'),
        about_history_archives: resolve(root, 'about-history-archives.html'),
        about_governance_leadership: resolve(root, 'about-governance-leadership.html'),
        about_policies_procedures: resolve(root, 'about-policies-procedures.html'),
        about_vacancies: resolve(root, 'about-vacancies.html'),
        contact: resolve(root, 'contact.html'),
        privacy_policy: resolve(root, 'privacy-policy.html'),
        components: resolve(root, 'components.html'),
      },
    },
  },
})
