import './style.css'

// Register every wf-* component once — available on every multi-page screen.
import './components/header-nav'
import './components/footer'
import './components/homepage-hero'
import './components/standard-hero'
import './components/page-header'
import './components/text'
import './components/text-media'
import './components/media'
import './components/quote'
import './components/logos'
import './components/statistics'
import './components/table'
import './components/calendar'
import './components/cards'
import './components/timeline'
import './components/form'
import './components/signup-form'
import './components/promo'
import './components/accordion'
import './components/share'
import './components/page-body'
import './components/prototype-nav'
import './components/palette-page'
